name: SIMS Primary Online Help

markdown: kramdown

permalink: none

title: SIMS Help

collections:
  glossary:
    output: false 
  docs:
    output: true
  broadcast:
    output: true
  images:
    output: true

defaults:
- scope:
    path: ""
    type: docs
  values:
    layout: docs
    navkey: help
    homeurl: docs
- scope:
    path: "_docs/whats-new"
  values:   
    header: What's New
    navkey: whatsnew
    homeurl: docs/whats-new

exclude: ['_site', 'node_modules', 'src']

sass:
  sass_dir: _sass
  style: compressed